on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Fuzz

jobs:
  fuzz:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: mjkoo/giftwrap-action@master
        with:
          cargo-fuzz-target: packet_parser
        env:
          MAYHEM_TOKEN: ${{ secrets.MAYHEM_TOKEN }}
          MAYHEM_URL: ${{ secrets.MAYHEM_URL }}
