on:
#   push:
#     branches: [ master ]

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Fuzz

jobs:
  fuzz:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install cargo-fuzz
        # Fix for cargo-fuzz on latest nightly: https://github.com/rust-fuzz/cargo-fuzz/issues/276
        # Switch back to installing from crates.io when it's released.
        #run: cargo install cargo-fuzz
        run: cargo install --git https://github.com/rust-fuzz/cargo-fuzz --rev b4df3e58f767b5cad8d1aa6753961003f56f3609
#       - name: Fuzz
#         run: cargo fuzz run packet_parser -- -max_len=1536 -max_total_time=30
      - name: Build Fuzzer
        run: cargo fuzz build packet_parser
      - name: Run Mayhem
        run: >-
          docker run 
          -e MAYHEM_URL=${{ secrets.MAYHEM_URL }}
          -e MAYHEM_TOKEN=${{ secrets.MAYHEM_TOKEN }}
          -v /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu 
          -v /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu 
          -v ${{ runner.workspace }}/fuzz/corpus/packet_parser:/corpus
          -v ${{ runner.workspace }}/fuzz/target/x86_64-unknown-linux-gnu/release/packet_parser:/packet_parser 
          -it forallsecure/mcode-cli:1.15 
          /bin/sh -c 'mayhem package /packet_parser -o /package/; run=`mayhem run /package --baseimage ubuntu:20.04 --corpus file:///corpus --dynamic --duration 30`; mayhem wait $run; [[ `mayhem show $run | grep Defects | awk "{print \$NF}"` == 0 ]]'
