on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Fuzz

jobs:
  fuzz:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - uses: mjkoo/mcode-action@main
        with:
          cargo-fuzz-target: packet_parser
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          mayhem-url: ${{ secrets.MAYHEM_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
