on:
#   push:
#     branches: [ master ]

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Fuzz

jobs:
  fuzz:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install cargo-fuzz
        # Fix for cargo-fuzz on latest nightly: https://github.com/rust-fuzz/cargo-fuzz/issues/276
        # Switch back to installing from crates.io when it's released.
        run: cargo install --git https://github.com/rust-fuzz/cargo-fuzz --rev b4df3e58f767b5cad8d1aa6753961003f56f3609

      - uses: ethan42/mcode-action@36dfb8e498a0a403d34df1f9e914256d19e9764f
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          mayhem-url: ${{ secrets.MAYHEM_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image: ubuntu:20.04
